### ISSUE TITLE
Translation > Get shared contact dialog has not been translated

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-contacts#64]
# Actual Result

Get shared contact dialog has not been translated into other languages. It's always English

![trans_vi](https://user-images.githubusercontent.com/69950655/92893363-ce56c280-f443-11ea-877c-0b7afd7853c4.png)

# Expected Result

It should be translated into the corresponding languages. 

# Steps

1. Navigate to Contact module
2. Click here
![image](https://user-images.githubusercontent.com/69950655/92893610-078f3280-f444-11ea-9392-e1bcb0d46633.png)

**Comment by asmaNode** [comment]
@tlle14 I think it is fixed 
![adressBookBug](https://user-images.githubusercontent.com/43316837/94703770-1d9f5d00-0337-11eb-9d56-adb01fde81b1.gif)

**Comment by asmaNode** [comment]
@tlle14  please can you specify wich  browser you use for this test ?

**Comment by tlle14** [comment]
> @tlle14 please can you specify wich browser you use for this test ?

Hi @asmaNode 

I still see the issue on Production. I'm using Chrome 84.0 on Ubuntu

**Comment by tlle14** [comment]
As I observe, the issue won't happen when you're using an incognito browser. 

It might happen when you open other applications (inbox/calendar) without refreshing them. So I guess this bug is from the way we save language property. 

Please investigate. Thanks!

**Comment by huy-ta** [comment]
> @tlle14 , when you update the language , you must refresh each SPA opened @huy-ta @renaudboyer i guess it is the expected behaviour no?

Yes it is expected.

**Comment by asmaNode** [comment]
so it not a bug !
